import React from 'react';
import Head from 'next/head';
import Image from 'next/image';

import { Card } from '@components/card';
import Link from 'next/link';
import { Button } from 'antd';

import styles from '@styles/Home.module.less';

export default function AppHome() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to your APP-1</h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/app-1/index.js</code>
          <br />
          <br />
          Demonstrate public var is{' '}
          <code className={styles.code}>{`NEXT_PUBLIC_VAR = ${process.env.NEXT_PUBLIC_VAR}`}</code>
          declaring in <code className={styles.code}>.env</code>
        </p>

        <Button type="primary" size="large">
          <Link href="app-1/dashboard">
            <a>Open Dashboard</a>
          </Link>
        </Button>

        <div className={styles.grid}>
          <Card
            url="https://nextjs.org/docs"
            title="Documentation"
            text="Find in-depth information about Next.js features and API."
          />

          <Card
            url="https://nextjs.org/learn"
            title="Learn"
            text="Learn about Next.js in an interactive course with quizzes!"
          />

          <Card
            url="https://github.com/vercel/next.js/tree/master/examples"
            title="Examples"
            text="Discover and deploy boilerplate example Next.js projects."
          />

          <Card
            url="https://vercel.com/import?filter=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy"
            text="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Template by Platformerie</p>
        <a href="https://vercel.com" target="_blank" rel="noopener noreferrer">
          Powered by <img src="/vercel.svg" alt="Vercel Logo" className={styles.logo} />
        </a>
      </footer>
    </div>
  );
}
